name: Build and Push images
run-name: Build images
on:
  workflow_call:
    inputs:
      src_branch:
        type: string
        default: ''
        description: 'Source branch to build KFP from'
        required: false
      target_tag:
        type: string
        description: 'Target Image Tag'
        required: true
      arch_tag:
        type: string
        description: 'Architecture tag suffix e.g. amd64 or arm64'
        required: true
      overwrite_imgs:
        type: string
        default: 'true'
        description: 'Overwrite images in GHCR if they already exist for this tag.'
        required: false
      set_latest:
        type: string
        default: 'true'
        description: 'Set latest tag on build images.'
        required: false
      add_sha_tag:
        type: string
        default: 'true'
        description: 'Add a sha image tag.'
        required: false
      app_to_build:
        type: string
        description: 'Provide the app name to build'
        required: true
      image_context:
        type: string
        description: 'Provide the docker file path'
        required: true
      docker_file:
        type: string
        description: 'Provide the docker file name'
        required: true
      platforms:
        type: string
        required: true
        description: e.g, linux/amd64 or linux/arm64
      runs_on:
        type: string
        required: true
        description: 'Runner label to execute on'
      push:
        type: boolean
        default: false
        description: 'Whether to push image to CR or not'
        required: false
  workflow_dispatch:
    inputs:
      src_branch:
        type: string
        default: ''
        description: 'Source branch to build KFP from'
        required: true
      target_tag:
        type: string
        default: 'X.Y.Z'
        description: 'Target Image Tag'
        required: true
      arch_tag:
        type: string
        default: 'amd64'
        description: 'Architecture tag suffix e.g. amd64 or arm64'
        required: true
      fail_fast:
        type: string
        default: 'true'
        description: 'Stop running entire Workflow if a single build fails'
        required: true
      overwrite_imgs:
        type: string
        default: 'true'
        description: 'Overwrite images in GHCR if they already exist for this tag.'
        required: true
      set_latest:
        type: string
        default: 'true'
        description: 'Set latest tag on build images.'
        required: true
      add_sha_tag:
        type: string
        default: 'true'
        description: 'Add a sha image tag.'
        required: false
      app_to_build:
        type: string
        default: ''
        description: 'Provide the app name to build'
        required: true
      image_context:
        type: string
        default: ''
        description: 'Provide the docker file path'
        required: true
      docker_file:
        type: string
        default: ''
        description: 'Provide the docker file name'
        required: true
      platforms:
        type: string
        default: ''
        required: true
        description: 'Provide the target architecture e.g, linux/amd64, linux/arm64'
      runs_on:
        type: string
        required: true
        description: 'Runner label to execute on'
      push:
        type: boolean
        default: false
        description: 'Whether to push image to CR or not'
        required: true
env:
  SOURCE_BRANCH: ${{ inputs.src_branch }}
  TARGET_IMAGE_TAG: ${{ inputs.target_tag }}
  OVERWRITE_IMAGES: ${{ inputs.overwrite_imgs }}
  IMAGE_REGISTRY: ghcr.io
  IMAGE_ORG: ${{ github.repository_owner }}
  SET_LATEST: ${{ inputs.set_latest }}
  ADD_SHA_TAG: ${{ inputs.add_sha_tag }}
  CACHE_PATH: '/tmp/.buildx-cache'

jobs:
  build-and-push-images:
    continue-on-error: false
    runs-on: ${{ inputs.runs_on }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{env.SOURCE_BRANCH}}

      - name: Get checked-out commit SHA
        id: get_commit
        run: echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Check if image tag already exists
        id: check_tag
        env:
          IMAGE: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_ORG }}/${{ inputs.app_to_build }}:${{env.TARGET_IMAGE_TAG}}-${{inputs.arch_tag}}
          OVERWRITE: ${{ env.OVERWRITE_IMAGES }}
        run: |
          if docker manifest inspect "${IMAGE}" > /dev/null 2>&1; then
            echo "Image tag already exists!"
            if [ "$OVERWRITE" == "false" ]; then
              echo "Overwrite is set to false, exiting."
              exit 1
            else
              echo "Overwrite is set to true, proceeding with push."
            fi
          else
            echo "No tag conflict, safe to push."
          fi

      # This step uses docker/metadata-action to extract tags and labels
      # that will be applied to the specified image. The id "meta" allows
      # the output of this step to be referenced in a subsequent step.
      # The images value provides the base name for the tags and labels.
      - name: Extract metadata (tags, labels) for Build
        id: meta
        uses: docker/metadata-action@v5
        if: steps.check_tag.outcome == 'success'
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_ORG }}/${{ inputs.app_to_build }}

      # Build the image. If the build succeeds, it pushes the image to GitHub
      # Packages. It uses the context parameter to define the build's context
      # as the set of files located in the specified path.
      - name: Build and push Image
        id: push
        uses: docker/build-push-action@v6
        if: steps.check_tag.outcome == 'success'
        with:
          platforms: ${{ inputs.platforms }}
          context: ${{ inputs.image_context }}
          file: ${{ inputs.docker_file }}
          push: ${{ inputs.push }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_ORG }}/${{ inputs.app_to_build }},push-by-digest=true,name-canonical=true,push=${{ inputs.push }}
          build-args: |
            COMMIT_SHA=${{ steps.get_commit.outputs.sha }}
            COMMIT_HASH=${{ steps.get_commit.outputs.sha }}
            TAG_NAME=${{ inputs.target_tag }}

      # Export the digest
      - name: Export digest
        if: steps.check_tag.outcome == 'success' && inputs.push
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.push.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      # Upload the digest
      - name: Upload digest
        if: steps.check_tag.outcome == 'success' && inputs.push
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ inputs.app_to_build }}-${{ inputs.arch_tag }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

      # This step generates an artifact attestation for the image
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        if: steps.check_tag.outcome == 'success' && inputs.push
        with:
          subject-name: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_ORG }}/${{ inputs.app_to_build }}
          subject-digest: ${{ steps.push.outputs.digest }}
