name: KFP SDK Tests

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - 'api/**'
      - 'sdk/**'
      - 'test_data/sdk_compiled_pipelines/**'
      - './test/presubmit-tests-sdk.sh'
      - '.github/workflows/kfp-sdk-tests.yml'
      - '!**/*.md'
      - '!**/OWNERS'

concurrency:
  group: sdk-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  sdk-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      matrix:
        python-version: ['3.10', '3.13']

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Generate proto files
      id: install-protobuf-deps
      uses: ./.github/actions/protobuf

    - name: Build & install kfp
      id: install-kfp-k8s-deps
      uses: ./.github/actions/kfp-k8s

    - name: Install Test dependencies
      run: |
        pip install -r sdk/python/requirements-dev.txt
        pip install google_cloud_pipeline_components

    - name: Run SDK Tests
      env:
        # We setup the env in the CI
        SETUP_ENV: false
        REPO_NAME: ${{ github.repository }}
        PULL_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        ./test/presubmit-tests-sdk.sh
